import { AppUser, Client, CompanyProfile, Equipment, Invoice, LaborService, ServiceOrder } from './types';

export const initialUsers: AppUser[] = [
  {
    id: 'usr-master-ivo',
    name: 'Ivo (Master Administrador)',
    email: 'ivoaltctrl@gmail.com',
    section: 'Diretoria & Governança',
    roleTitle: 'Administrador Geral & Mestre',
    department: 'Governança & TI',
    password: 'admin',
    privilege: 'administrador',
    privilegeLabel: 'Administrador Master Geral',
    canValidateBilling: true,
    canDeleteOS: true,
    canAccessExecutive: true,
    canAccessSettings: true,
    mustChangePassword: false,
    firstAccess: false,
    active: true,
    createdAt: '2026-01-01T00:00:00.000Z',
    role: 'master_ti',
    roleLabel: 'Administrador de TI & Governança',
    phone: '(11) 99999-0000',
    avatarColor: 'bg-slate-900',
  },
  {
    id: 'usr-1',
    name: 'Mariana Costa',
    email: 'mariana.costa@wfs.aero',
    section: 'Faturamento',
    roleTitle: 'Analista de Faturamento Pleno',
    department: 'Controladoria & Cobrança',
    password: '123',
    privilege: 'supervisor', // Analista com privilégio de supervisor para cobrir supervisão
    privilegeLabel: 'Supervisor de Operações (Cobertura)',
    canValidateBilling: true,
    canDeleteOS: true,
    canAccessExecutive: true,
    canAccessSettings: true,
    active: true,
    createdAt: '2026-01-15T08:00:00.000Z',
    role: 'faturamento',
    roleLabel: 'Analista de Faturamento & Cobrança',
    phone: '(11) 96543-2109',
    avatarColor: 'bg-emerald-600',
  },
  {
    id: 'usr-2',
    name: 'Roberto Santos',
    email: 'roberto.santos@wfs.aero',
    section: 'Pista & Rampa',
    roleTitle: 'Supervisor Geral de Rampa',
    department: 'Operações GSE',
    password: '123',
    privilege: 'supervisor',
    privilegeLabel: 'Supervisor de Operações',
    canValidateBilling: true,
    canDeleteOS: true,
    canAccessExecutive: true,
    canAccessSettings: true,
    active: true,
    createdAt: '2026-01-10T08:00:00.000Z',
    role: 'supervisor',
    roleLabel: 'Supervisor Geral de Operações',
    phone: '(11) 95432-1098',
    avatarColor: 'bg-red-600',
  },
  {
    id: 'usr-3',
    name: 'Amanda Aparecida Vasco Cortez',
    email: 'amanda.cortez@wfs.aero',
    section: 'Atendimento / Rampa',
    roleTitle: 'Encarregada de Operações de Solo',
    department: 'Operações Pátio',
    password: '123',
    privilege: 'supervisor',
    privilegeLabel: 'Supervisor de Operações',
    canValidateBilling: true,
    canDeleteOS: true,
    canAccessExecutive: true,
    canAccessSettings: false,
    active: true,
    createdAt: '2026-02-01T08:00:00.000Z',
    role: 'operador_campo',
    roleLabel: 'Encarregada de Campo & Pista',
    phone: '(11) 98765-1122',
    avatarColor: 'bg-indigo-600',
  },
  {
    id: 'usr-4',
    name: 'Carlos Silva',
    email: 'carlos.silva@wfs.aero',
    section: 'Pista',
    roleTitle: 'Operador GSE Especializado',
    department: 'Operações Solo',
    password: '123',
    privilege: 'operador',
    privilegeLabel: 'Operador de Solo / Campo',
    canValidateBilling: false,
    canDeleteOS: false,
    canAccessExecutive: false,
    canAccessSettings: false,
    active: true,
    createdAt: '2026-02-15T08:00:00.000Z',
    role: 'operador_campo',
    roleLabel: 'Operador GSE de Pista',
    phone: '(11) 98765-4321',
    avatarColor: 'bg-amber-600',
  },
  {
    id: 'usr-5',
    name: 'Lucas Mendes',
    email: 'lucas.mendes@wfs.aero',
    section: 'Manutenção GSE',
    roleTitle: 'Técnico Especialista em Solo',
    department: 'Engenharia & Equipamentos',
    password: '123',
    privilege: 'analista',
    privilegeLabel: 'Analista Técnico',
    canValidateBilling: true,
    canDeleteOS: false,
    canAccessExecutive: true,
    canAccessSettings: false,
    active: true,
    createdAt: '2026-02-20T08:00:00.000Z',
    role: 'tecnico',
    roleLabel: 'Técnico Especialista em Solo',
    phone: '(11) 97654-3210',
    avatarColor: 'bg-blue-600',
  },
  {
    id: 'usr-6',
    name: 'TI Administrador',
    email: 'ti.brasil@wfs.aero',
    section: 'Governança & TI',
    roleTitle: 'Coordenador de TI & Sistemas',
    department: 'Tecnologia da Informação',
    password: 'admin',
    privilege: 'administrador',
    privilegeLabel: 'Administrador Master',
    canValidateBilling: true,
    canDeleteOS: true,
    canAccessExecutive: true,
    canAccessSettings: true,
    active: true,
    createdAt: '2026-01-01T08:00:00.000Z',
    role: 'master_ti',
    roleLabel: 'Administrador de TI & Governança',
    phone: '(11) 4002-8922',
    avatarColor: 'bg-slate-800',
  },
];

export const initialCompany: CompanyProfile = {
  name: 'WFS Brasil Serviços Aeroportuários e Operações Industriais Ltda',
  tradeName: 'WFS - A SATS COMPANY',
  cnpj: '02.481.932/0001-50',
  stateRegistration: '114.920.301.119',
  phone: '(11) 4002-8922',
  email: 'faturamento.brasil@wfs.aero',
  address: 'Aeroporto Internacional de Guarulhos - Terminal de Cargas / Hangar WFS',
  cityState: 'Guarulhos - SP',
  pixKey: '02481932000150',
  bankInfo: 'Banco Santander (033) - Ag: 2240 / CC: 93810-4',
  defaultTerms: 'O cliente declara estar ciente do recebimento dos equipamentos em perfeito estado de funcionamento e/ou da prestação dos serviços especializados discriminados nesta Ordem de Serviço conforme os padrões operacionais WFS. A recusa injustificada de aceite não desobriga o pagamento das diárias e horas apontadas.',
  billingAlertHours: 24,
};

export const initialClients: Client[] = [
  {
    id: 'cli-ita',
    name: 'ITA AIRWAYS',
    tradeName: 'ITA Airways Brasil / Operações GRU',
    document: '33.912.876/0001-90',
    email: 'groundops.gru@ita-airways.com',
    phone: '11984210099',
    contactPerson: 'Amanda Aparecida Vasco Cortez',
    address: {
      street: 'Aeroporto Internacional de Guarulhos',
      number: 'TPS3',
      neighborhood: 'Cumbica',
      city: 'Guarulhos',
      state: 'SP',
      zipCode: '07190-100',
      workSiteName: 'GRU - Terminal de Passageiros & Pátio',
    },
    paymentTermsDays: 15,
    notes: 'Serviços auxiliares de transporte aéreo e atendimento de rampa em voos e cancelamentos.',
    createdAt: '2026-08-11T14:34:00.000Z',
  },
  {
    id: 'cli-atacado',
    name: 'Atacado bom preço',
    tradeName: 'Atacado Bom Preço Distribuição Ltda',
    document: '15.238.396/0001-87',
    email: 'manutencao@atacadobompreco.com.br',
    phone: '11973129840',
    contactPerson: 'João C. Silva',
    address: {
      street: 'Av. Senador Salgado Filho',
      number: '1305',
      neighborhood: 'Centro',
      city: 'Guarulhos',
      state: 'SP',
      zipCode: '07115-000',
      workSiteName: 'Centro de Distribuição Guarulhos',
    },
    paymentTermsDays: 30,
    notes: 'Manutenção corretiva com troca de filtros, suporte e mangueiras.',
    createdAt: '2021-02-26T08:00:00.000Z',
  },
  {
    id: 'cli-1',
    name: 'LATAM Airlines Brasil S.A.',
    tradeName: 'LATAM Cargo & Ground Operations',
    document: '02.012.862/0001-60',
    email: 'ground.operations@latam.com',
    phone: '11984210099',
    contactPerson: 'Coord. Marcelo Ribeiro',
    address: {
      street: 'Rod. Hélio Smidt, s/n',
      number: 'Hangar 04',
      neighborhood: 'Cumbica',
      city: 'Guarulhos',
      state: 'SP',
      zipCode: '07190-100',
      workSiteName: 'Pátio 2 - Pista & Hangar LATAM',
    },
    paymentTermsDays: 15,
    notes: 'Exige canhoto de OS assinado pelo supervisor de pátio na hora para autorizar a medição.',
    createdAt: '2026-01-10T10:00:00.000Z',
  },
  {
    id: 'cli-2',
    name: 'Azul Linhas Aéreas Brasileiras S.A.',
    tradeName: 'Azul Cargo Express',
    document: '09.296.295/0001-60',
    email: 'operacoes.cargo@voeazul.com.br',
    phone: '11973129840',
    contactPerson: 'Carlos Alberto (Supervisor de Turno)',
    address: {
      street: 'Av. Marcos Penteado de Ulhôa Rodrigues, 939',
      number: 'Ed. Castelo',
      neighborhood: 'Tamboré',
      city: 'Barueri',
      state: 'SP',
      zipCode: '06460-040',
      workSiteName: 'TECA Viracopos (VCP) - Campinas',
    },
    paymentTermsDays: 30,
    notes: 'Faturamento quinzenal agrupado por centro de custo de pista.',
    createdAt: '2026-01-15T14:30:00.000Z',
  },
  {
    id: 'cli-3',
    name: 'Lufthansa Cargo AG - Filial Brasil',
    tradeName: 'Lufthansa Cargo Handling',
    document: '33.123.456/0001-77',
    email: 'handling.gru@dlh.de',
    phone: '11999887766',
    contactPerson: 'Klaus Mueller',
    address: {
      street: 'Rod. Pres. Dutra, km 215',
      number: 'Terminal TECA',
      neighborhood: 'Cumbica',
      city: 'Guarulhos',
      state: 'SP',
      zipCode: '07180-000',
      workSiteName: 'TECA GRU - Doca 08',
    },
    paymentTermsDays: 7,
    notes: 'Prioridade máxima em pontualidade de entrega dos tratores de pátio.',
    createdAt: '2026-01-20T08:00:00.000Z',
  },
  {
    id: 'cli-4',
    name: 'CCR Aeroportos S.A.',
    tradeName: 'Concessionária do Aeroporto de Curitiba & BH',
    document: '14.765.432/0001-55',
    email: 'manutencao.pista@grupoccr.com.br',
    phone: '19981234567',
    contactPerson: 'Eng. Fernando Souza',
    address: {
      street: 'Av. Rocha Pombo, s/n',
      number: 'Administração',
      neighborhood: 'Águas Belas',
      city: 'São José dos Pinhais',
      state: 'PR',
      zipCode: '83010-900',
      workSiteName: 'Pista de Pouso e Pátio Central',
    },
    paymentTermsDays: 30,
    notes: 'Exige laudo técnico assinado e fotos de antes/depois da manutenção eletromecânica.',
    createdAt: '2026-02-01T11:20:00.000Z',
  }
];

export const initialEquipments: Equipment[] = [
  {
    id: 'eq-1',
    code: 'GPU-090',
    name: 'Ground Power Unit (GPU) 90kVA 400Hz para Aeronaves',
    category: 'Energia GSE Aeroportuária',
    dailyRate: 1200.00,
    hourlyRate: 180.00,
    status: 'disponivel',
    serialNumber: 'GPU-2024-9981',
    specifications: 'Saída 115/200V 400Hz Trifásico, motor Cummins Diesel silenciado, cabo padrão aeronáutico.',
  },
  {
    id: 'eq-2',
    code: 'TRB-015',
    name: 'Trator de Reboque de Pista (Baggage Tow Tractor)',
    category: 'Movimentação GSE',
    dailyRate: 950.00,
    hourlyRate: 140.00,
    status: 'em_uso',
    serialNumber: 'TR-EL-401',
    specifications: 'Capacidade de tração de até 25 toneladas de carga/carretas de bagagem, motor elétrico com bateria íon-lítio.',
  },
  {
    id: 'eq-3',
    code: 'EST-020',
    name: 'Esteira Carregadora de Bagagens Autopropelida (Belt Loader)',
    category: 'Carga & Descarga',
    dailyRate: 850.00,
    hourlyRate: 130.00,
    status: 'disponivel',
    serialNumber: 'BL-884-2023',
    specifications: 'Elevação hidráulica ajustável até 4.3m, compatível com narrow-body e wide-body.',
  },
  {
    id: 'eq-4',
    code: 'GER-050',
    name: 'Grupo Gerador Silenciado 50 kVA Diesel',
    category: 'Geradores Industriais',
    dailyRate: 480.00,
    monthlyRate: 7200.00,
    status: 'disponivel',
    serialNumber: 'GG-50-2022',
    specifications: 'Cabine silenciada 68dB, tanque de 150L, painel digital de comando.',
  },
  {
    id: 'eq-5',
    code: 'MNC-012',
    name: 'Caminhão Munck 12 Toneladas com Operador',
    category: 'Içamento Pesado',
    dailyRate: 1800.00,
    hourlyRate: 220.00,
    status: 'disponivel',
    serialNumber: 'MNC-VOLVO-77',
    specifications: 'Alcance vertical de 18 metros, capacidade máxima 12t no pé e 1.8t na ponta.',
  },
  {
    id: 'eq-6',
    code: 'PLT-010',
    name: 'Plataforma Tesoura Elétrica 10m (Manlift)',
    category: 'Trabalho em Altura',
    dailyRate: 450.00,
    monthlyRate: 5800.00,
    status: 'disponivel',
    serialNumber: 'PLT-JLG-102',
    specifications: 'Altura de trabalho 10m, capacidade 230kg, pneus não marcantes para hangares.',
  }
];

export const initialLaborServices: LaborService[] = [
  {
    id: 'lab-1',
    code: 'MO-GSE-01',
    name: 'Operador de Equipamentos de Solo GSE Especializado',
    category: 'Operação Aeroportuária',
    unit: 'hora',
    unitPrice: 90.00,
    description: 'Profissional credenciado pela ANAC e INFRAERO com credencial de pista válida.',
  },
  {
    id: 'lab-2',
    code: 'MO-GSE-02',
    name: 'Técnico de Manutenção Eletromecânica / GSE',
    category: 'Manutenção Técnica',
    unit: 'hora',
    unitPrice: 110.00,
    description: 'Diagnóstico e reparo preventivo/corretivo em esteiras, tratores, geradores e GPUs.',
  },
  {
    id: 'lab-3',
    code: 'MO-IND-03',
    name: 'Soldador TIG / MIG Industrial com Certificação',
    category: 'Serralheria & Estrutura',
    unit: 'diaria',
    unitPrice: 550.00,
    description: 'Soldagem de alta precisão em tubulações e estruturas metálicas de hangares.',
  },
  {
    id: 'lab-4',
    code: 'MO-ENG-04',
    name: 'Engenheiro de Operações & Emissão de ART Técnica',
    category: 'Engenharia',
    unit: 'servico_fechado',
    unitPrice: 1200.00,
    description: 'Vistoria técnica presencial com laudo de conformidade e responsabilidade técnica.',
  },
  {
    id: 'lab-5',
    code: 'MO-CARGO-05',
    name: 'Equipe Especializada de Carga Aérea (1 Líder + 3 Auxiliares)',
    category: 'Carga & Descarga TECA',
    unit: 'diaria',
    unitPrice: 1600.00,
    description: 'Montagem de pallets aeronáuticos ULD e amarração com redes certificadas IATA.',
  }
];

const sampleClientSignatureSVG = `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="300" height="100" viewBox="0 0 300 100"><path d="M 20 60 Q 60 10, 100 40 T 180 30 T 260 70 M 70 80 L 220 75" stroke="%23E5232A" stroke-width="3" fill="none" stroke-linecap="round"/></svg>`;
const sampleTechSignatureSVG = `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="300" height="100" viewBox="0 0 300 100"><path d="M 30 70 Q 70 20, 120 50 Q 180 80, 240 30 M 100 30 L 150 90" stroke="%230F172A" stroke-width="3" fill="none" stroke-linecap="round"/></svg>`;

export const initialOrders: ServiceOrder[] = [
  // OS 31877 - CANCELAMENTO DE VOO AZ675 (ITA AIRWAYS) - Registros reais da Planilha
  {
    id: 'os-31877-1',
    osNumber: '31877',
    clientId: 'cli-ita',
    clientName: 'ITA AIRWAYS',
    clientDocument: '',
    clientPhone: '(11) 98421-0099',
    clientEmail: 'groundops.gru@ita-airways.com',
    workLocation: 'GRU',
    category: 'misto',
    title: 'CANCELAMENTO DE VOO AZ675',
    description: 'Serviços Auxiliares de Transporte Aéreo - Atendimento Operacional de Pista e Rampa',
    status: 'aguardando_validacao',
    agentName: 'AMANDA APARECIDA VASCO CORTEZ 14286',
    agentBadge: '14286',
    startTime: '14:34',
    endTime: '20:10',
    durationMinutes: 336,
    durationFormatted: '5h 36m',
    quantity: '-',
    filledBy: 'Amanda Aparecida Vasco Cortez',
    createdBy: 'Amanda Aparecida Vasco Cortez',
    createdByRole: 'Encarregado de Campo & Pista',
    createdOrigin: 'campo_app',
    scheduledDate: '2026-08-11',
    scheduledTime: '14:34',
    createdAt: '2026-08-11T14:34:00.000Z',
    completedAt: '2026-08-11T20:10:00.000Z',
    technicianName: 'AMANDA APARECIDA VASCO CORTEZ 14286',
    canhotoUrl: 'https://drive.google.com/open?id=wfs-az675-01',
    equipmentItems: [],
    laborItems: [
      {
        id: 'lab-31877-1',
        laborServiceId: 'lab-1',
        name: 'Operação de Pista / Voo AZ675: Amanda Aparecida',
        unit: 'hora',
        quantity: 5.6,
        unitPrice: 0,
        technicianName: 'Amanda Aparecida Vasco Cortez',
      }
    ],
    materialItems: [],
    discount: 0,
    addition: 0,
    totalAmount: 0,
    checklist: [
      { id: 'chk-31877-1', task: 'Inspeção de segurança FOD na posição da aeronave', completed: true },
      { id: 'chk-31877-2', task: 'Atendimento e triagem de bagagens de voo cancelado AZ675', completed: true },
    ],
    photos: [
      {
        id: 'p-31877-1',
        url: 'https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?auto=format&fit=crop&w=600&q=80',
        title: 'Canhoto de Pista Digitalizado (Google Drive)',
        category: 'canhoto',
        timestamp: '2026-08-11T20:10:00.000Z',
      }
    ],
    clientSignature: {
      signatureImage: sampleClientSignatureSVG,
      signerName: 'Líder de Turno ITA Airways',
      signerDocument: '33.912.876/0001-90',
      signerRole: 'Coordenador Operações ITA GRU',
      signedAt: '2026-08-11T20:10:00.000Z',
    },
  },
  {
    id: 'os-31877-2',
    osNumber: '31877',
    clientId: 'cli-ita',
    clientName: 'ITA AIRWAYS',
    clientDocument: '',
    clientPhone: '(11) 98421-0099',
    clientEmail: 'groundops.gru@ita-airways.com',
    workLocation: 'Aeroporto / Pista',
    category: 'locacao',
    title: 'CANCELAMENTO DE VOO AZ675',
    description: 'Atendimento GSE de Rampa e Locação de Equipamentos',
    status: 'aguardando_validacao',
    agentName: 'MARIA EDUARDA QUEIROZ FERREIRA 35629',
    agentBadge: '35629',
    startTime: '12:00',
    endTime: '19:00',
    durationMinutes: 420,
    durationFormatted: '7h 00m',
    quantity: '-',
    filledBy: 'Amanda Aparecida Vasco Cortez',
    createdBy: 'Amanda Aparecida Vasco Cortez',
    createdByRole: 'Encarregado de Campo',
    createdOrigin: 'campo_app',
    scheduledDate: '2026-08-11',
    scheduledTime: '12:00',
    createdAt: '2026-08-11T12:00:00.000Z',
    completedAt: '2026-08-11T19:00:00.000Z',
    technicianName: 'MARIA EDUARDA QUEIROZ FERREIRA 35629',
    canhotoUrl: 'https://drive.google.com/open?id=wfs-az675-02',
    equipmentItems: [],
    laborItems: [],
    materialItems: [],
    discount: 0,
    addition: 0,
    totalAmount: 0,
    checklist: [],
    photos: [],
    clientSignature: {
      signatureImage: sampleClientSignatureSVG,
      signerName: 'Líder Operações ITA',
      signerDocument: '',
      signerRole: 'Coordenador',
      signedAt: '2026-08-11T19:00:00.000Z',
    },
  },
  {
    id: 'os-31877-3',
    osNumber: '31877',
    clientId: 'cli-ita',
    clientName: 'ITA AIRWAYS',
    clientDocument: '',
    clientPhone: '(11) 98421-0099',
    clientEmail: 'groundops.gru@ita-airways.com',
    workLocation: 'Aeroporto / Pista',
    category: 'locacao',
    title: 'CANCELAMENTO DE VOO AZ675',
    description: 'Movimentação e manobra de pista com trator de reboque',
    status: 'aguardando_validacao',
    agentName: 'MIGUEL DA SILVA SANTANA 28794',
    agentBadge: '28794',
    startTime: '13:40',
    endTime: '19:40',
    durationMinutes: 360,
    durationFormatted: '6h 00m',
    quantity: '-',
    filledBy: 'Amanda Aparecida Vasco Cortez',
    createdBy: 'Amanda Aparecida Vasco Cortez',
    createdOrigin: 'campo_app',
    scheduledDate: '2026-08-11',
    createdAt: '2026-08-11T13:40:00.000Z',
    completedAt: '2026-08-11T19:40:00.000Z',
    technicianName: 'MIGUEL DA SILVA SANTANA 28794',
    canhotoUrl: 'https://drive.google.com/open?id=wfs-az675-03',
    equipmentItems: [],
    laborItems: [],
    materialItems: [],
    discount: 0,
    addition: 0,
    totalAmount: 0,
    checklist: [],
    photos: [],
  },
  {
    id: 'os-31877-4',
    osNumber: '31877',
    clientId: 'cli-ita',
    clientName: 'ITA AIRWAYS',
    clientDocument: '',
    clientPhone: '(11) 98421-0099',
    clientEmail: 'groundops.gru@ita-airways.com',
    workLocation: 'Aeroporto / Pista',
    category: 'locacao',
    title: 'CANCELAMENTO DE VOO AZ675',
    description: 'Atendimento de solo na posição remota',
    status: 'aguardando_validacao',
    agentName: 'ANNA CAROLINA GOMES SANTOS 28180',
    agentBadge: '28180',
    startTime: '14:05',
    endTime: '20:16',
    durationMinutes: 371,
    durationFormatted: '6h 11m',
    quantity: '-',
    filledBy: 'Amanda Aparecida Vasco Cortez',
    createdBy: 'Amanda Aparecida Vasco Cortez',
    createdOrigin: 'campo_app',
    scheduledDate: '2026-08-11',
    createdAt: '2026-08-11T14:05:00.000Z',
    completedAt: '2026-08-11T20:16:00.000Z',
    technicianName: 'ANNA CAROLINA GOMES SANTOS 28180',
    canhotoUrl: 'https://drive.google.com/open?id=wfs-az675-04',
    equipmentItems: [],
    laborItems: [],
    materialItems: [],
    discount: 0,
    addition: 0,
    totalAmount: 0,
    checklist: [],
    photos: [],
  },
  {
    id: 'os-31877-5',
    osNumber: '31877',
    clientId: 'cli-ita',
    clientName: 'ITA AIRWAYS',
    clientDocument: '',
    clientPhone: '(11) 98421-0099',
    clientEmail: 'groundops.gru@ita-airways.com',
    workLocation: 'Aeroporto / Pista',
    category: 'locacao',
    title: 'CANCELAMENTO DE VOO AZ675',
    description: 'Suporte emergencial e transporte de bagagens',
    status: 'aguardando_validacao',
    agentName: 'STEPHANE BEZERRA FURTUOSO 24999',
    agentBadge: '24999',
    startTime: '15:01',
    endTime: '16:06',
    durationMinutes: 65,
    durationFormatted: '1h 05m',
    quantity: '-',
    filledBy: 'Amanda Aparecida Vasco Cortez',
    createdBy: 'Amanda Aparecida Vasco Cortez',
    createdOrigin: 'campo_app',
    scheduledDate: '2026-08-11',
    createdAt: '2026-08-11T15:01:00.000Z',
    completedAt: '2026-08-11T16:06:00.000Z',
    technicianName: 'STEPHANE BEZERRA FURTUOSO 24999',
    canhotoUrl: 'https://drive.google.com/open?id=wfs-az675-05',
    equipmentItems: [],
    laborItems: [],
    materialItems: [],
    discount: 0,
    addition: 0,
    totalAmount: 0,
    checklist: [],
    photos: [],
  },
  {
    id: 'os-31877-6',
    osNumber: '31877',
    clientId: 'cli-ita',
    clientName: 'ITA AIRWAYS',
    clientDocument: '',
    clientPhone: '(11) 98421-0099',
    clientEmail: 'groundops.gru@ita-airways.com',
    workLocation: 'Aeroporto / Pista',
    category: 'locacao',
    title: 'CANCELAMENTO DE VOO AZ675',
    description: 'Atendimento operacional TECA / Pista',
    status: 'aguardando_validacao',
    agentName: 'JOYCE OLIVEIRA DE PINHO 35142',
    agentBadge: '35142',
    startTime: '14:56',
    endTime: '16:06',
    durationMinutes: 70,
    durationFormatted: '1h 10m',
    quantity: '-',
    filledBy: 'Amanda Aparecida Vasco Cortez',
    createdBy: 'Amanda Aparecida Vasco Cortez',
    createdOrigin: 'campo_app',
    scheduledDate: '2026-08-11',
    createdAt: '2026-08-11T14:56:00.000Z',
    completedAt: '2026-08-11T16:06:00.000Z',
    technicianName: 'JOYCE OLIVEIRA DE PINHO 35142',
    canhotoUrl: 'https://drive.google.com/open?id=wfs-az675-06',
    equipmentItems: [],
    laborItems: [],
    materialItems: [],
    discount: 0,
    addition: 0,
    totalAmount: 0,
    checklist: [],
    photos: [],
  },
  {
    id: 'os-31877-7',
    osNumber: '31877',
    clientId: 'cli-ita',
    clientName: 'ITA AIRWAYS',
    clientDocument: '',
    clientPhone: '(11) 98421-0099',
    clientEmail: 'groundops.gru@ita-airways.com',
    workLocation: 'Aeroporto / Pista',
    category: 'locacao',
    title: 'CANCELAMENTO DE VOO AZ675',
    description: 'Triagem e descarregamento de aeronave cancelada',
    status: 'aguardando_validacao',
    agentName: 'CELINE NASCIMENTO DANTAS 26174',
    agentBadge: '26174',
    startTime: '14:56',
    endTime: '19:59',
    durationMinutes: 303,
    durationFormatted: '5h 03m',
    quantity: '-',
    filledBy: 'Amanda Aparecida Vasco Cortez',
    createdBy: 'Amanda Aparecida Vasco Cortez',
    createdOrigin: 'campo_app',
    scheduledDate: '2026-08-11',
    createdAt: '2026-08-11T14:56:00.000Z',
    completedAt: '2026-08-11T19:59:00.000Z',
    technicianName: 'CELINE NASCIMENTO DANTAS 26174',
    canhotoUrl: 'https://drive.google.com/open?id=wfs-az675-07',
    equipmentItems: [],
    laborItems: [],
    materialItems: [],
    discount: 0,
    addition: 0,
    totalAmount: 0,
    checklist: [],
    photos: [],
  },
  {
    id: 'os-31877-8',
    osNumber: '31877',
    clientId: 'cli-ita',
    clientName: 'ITA AIRWAYS',
    clientDocument: '',
    clientPhone: '(11) 98421-0099',
    clientEmail: 'groundops.gru@ita-airways.com',
    workLocation: 'Aeroporto / Pista',
    category: 'locacao',
    title: 'CANCELAMENTO DE VOO AZ675',
    description: 'Operação de rampa e descarregamento de ULDs',
    status: 'aguardando_validacao',
    agentName: 'LUCIANO HENRIQUE FERREIRA 17861',
    agentBadge: '17861',
    startTime: '15:15',
    endTime: '20:15',
    durationMinutes: 300,
    durationFormatted: '5h 00m',
    quantity: '-',
    filledBy: 'Amanda Aparecida Vasco Cortez',
    createdBy: 'Amanda Aparecida Vasco Cortez',
    createdOrigin: 'campo_app',
    scheduledDate: '2026-08-11',
    createdAt: '2026-08-11T15:15:00.000Z',
    completedAt: '2026-08-11T20:15:00.000Z',
    technicianName: 'LUCIANO HENRIQUE FERREIRA 17861',
    canhotoUrl: 'https://drive.google.com/open?id=wfs-az675-08',
    equipmentItems: [],
    laborItems: [],
    materialItems: [],
    discount: 0,
    addition: 0,
    totalAmount: 0,
    checklist: [],
    photos: [],
  },
  {
    id: 'os-31877-9',
    osNumber: '31877',
    clientId: 'cli-ita',
    clientName: 'ITA AIRWAYS',
    clientDocument: '',
    clientPhone: '(11) 98421-0099',
    clientEmail: 'groundops.gru@ita-airways.com',
    workLocation: 'Aeroporto / Pista',
    category: 'locacao',
    title: 'CANCELAMENTO DE VOO AZ675',
    description: 'Manobra de pista e tração de carretas',
    status: 'aguardando_validacao',
    agentName: 'VICTOR HUGO CORDEIRO SERAFIM 18887',
    agentBadge: '18887',
    startTime: '15:00',
    endTime: '20:13',
    durationMinutes: 313,
    durationFormatted: '5h 13m',
    quantity: '-',
    filledBy: 'Amanda Aparecida Vasco Cortez',
    createdBy: 'Amanda Aparecida Vasco Cortez',
    createdOrigin: 'campo_app',
    scheduledDate: '2026-08-11',
    createdAt: '2026-08-11T15:00:00.000Z',
    completedAt: '2026-08-11T20:13:00.000Z',
    technicianName: 'VICTOR HUGO CORDEIRO SERAFIM 18887',
    canhotoUrl: 'https://drive.google.com/open?id=wfs-az675-09',
    equipmentItems: [],
    laborItems: [],
    materialItems: [],
    discount: 0,
    addition: 0,
    totalAmount: 0,
    checklist: [],
    photos: [],
  },
  {
    id: 'os-31877-10',
    osNumber: '31877',
    clientId: 'cli-ita',
    clientName: 'ITA AIRWAYS',
    clientDocument: '',
    clientPhone: '(11) 98421-0099',
    clientEmail: 'groundops.gru@ita-airways.com',
    workLocation: 'Aeroporto / Pista',
    category: 'locacao',
    title: 'CANCELAMENTO DE VOO AZ675',
    description: 'Atendimento de pista e calços de aeronave',
    status: 'aguardando_validacao',
    agentName: 'VITOR FORNICITTI MELLONE 97866',
    agentBadge: '97866',
    startTime: '15:10',
    endTime: '20:13',
    durationMinutes: 303,
    durationFormatted: '5h 03m',
    quantity: '-',
    filledBy: 'Amanda Aparecida Vasco Cortez',
    createdBy: 'Amanda Aparecida Vasco Cortez',
    createdOrigin: 'campo_app',
    scheduledDate: '2026-08-11',
    createdAt: '2026-08-11T15:10:00.000Z',
    completedAt: '2026-08-11T20:13:00.000Z',
    technicianName: 'VITOR FORNICITTI MELLONE 97866',
    canhotoUrl: 'https://drive.google.com/open?id=wfs-az675-10',
    equipmentItems: [],
    laborItems: [],
    materialItems: [],
    discount: 0,
    addition: 0,
    totalAmount: 0,
    checklist: [],
    photos: [],
  },
  {
    id: 'os-31877-11',
    osNumber: '31877',
    clientId: 'cli-ita',
    clientName: 'ITA AIRWAYS',
    clientDocument: '',
    clientPhone: '(11) 98421-0099',
    clientEmail: 'groundops.gru@ita-airways.com',
    workLocation: 'Aeroporto / Pista',
    category: 'locacao',
    title: 'CANCELAMENTO DE VOO AZ675',
    description: 'Movimentação e entrega de bagagens extraviadas/retidas',
    status: 'aguardando_validacao',
    agentName: 'SAMIRA MISSON DOS SANTOS 37970',
    agentBadge: '37970',
    startTime: '13:56',
    endTime: '20:07',
    durationMinutes: 371,
    durationFormatted: '6h 11m',
    quantity: '-',
    filledBy: 'Amanda Aparecida Vasco Cortez',
    createdBy: 'Amanda Aparecida Vasco Cortez',
    createdOrigin: 'campo_app',
    scheduledDate: '2026-08-11',
    createdAt: '2026-08-11T13:56:00.000Z',
    completedAt: '2026-08-11T20:07:00.000Z',
    technicianName: 'SAMIRA MISSON DOS SANTOS 37970',
    canhotoUrl: 'https://drive.google.com/open?id=wfs-az675-11',
    equipmentItems: [],
    laborItems: [],
    materialItems: [],
    discount: 0,
    addition: 0,
    totalAmount: 0,
    checklist: [],
    photos: [],
  },
  {
    id: 'os-31877-12',
    osNumber: '31877',
    clientId: 'cli-ita',
    clientName: 'ITA AIRWAYS',
    clientDocument: '',
    clientPhone: '(11) 98421-0099',
    clientEmail: 'groundops.gru@ita-airways.com',
    workLocation: 'Aeroporto / Pista',
    category: 'locacao',
    title: 'CANCELAMENTO DE VOO AZ675',
    description: 'Auxílio na esteira de bagagem e triagem',
    status: 'aguardando_validacao',
    agentName: 'JULIA VIANA PAZ 29187',
    agentBadge: '29187',
    startTime: '14:00',
    endTime: '20:07',
    durationMinutes: 367,
    durationFormatted: '6h 07m',
    quantity: '-',
    filledBy: 'Amanda Aparecida Vasco Cortez',
    createdBy: 'Amanda Aparecida Vasco Cortez',
    createdOrigin: 'campo_app',
    scheduledDate: '2026-08-11',
    createdAt: '2026-08-11T14:00:00.000Z',
    completedAt: '2026-08-11T20:07:00.000Z',
    technicianName: 'JULIA VIANA PAZ 29187',
    canhotoUrl: 'https://drive.google.com/open?id=wfs-az675-12',
    equipmentItems: [],
    laborItems: [],
    materialItems: [],
    discount: 0,
    addition: 0,
    totalAmount: 0,
    checklist: [],
    photos: [],
  },
  {
    id: 'os-31877-13',
    osNumber: '31877',
    clientId: 'cli-ita',
    clientName: 'ITA AIRWAYS',
    clientDocument: '',
    clientPhone: '(11) 98421-0099',
    clientEmail: 'groundops.gru@ita-airways.com',
    workLocation: 'Aeroporto / Pista',
    category: 'locacao',
    title: 'CANCELAMENTO DE VOO AZ675',
    description: 'Acompanhamento do voo cancelado e translado de passageiros',
    status: 'aguardando_validacao',
    agentName: 'KEATLYNN LAVINIA RIBEIRO DA SILVA 26612',
    agentBadge: '26612',
    startTime: '13:55',
    endTime: '20:08',
    durationMinutes: 373,
    durationFormatted: '6h 13m',
    quantity: '-',
    filledBy: 'Amanda Aparecida Vasco Cortez',
    createdBy: 'Amanda Aparecida Vasco Cortez',
    createdOrigin: 'campo_app',
    scheduledDate: '2026-08-11',
    createdAt: '2026-08-11T13:55:00.000Z',
    completedAt: '2026-08-11T20:08:00.000Z',
    technicianName: 'KEATLYNN LAVINIA RIBEIRO DA SILVA 26612',
    canhotoUrl: 'https://drive.google.com/open?id=wfs-az675-13',
    equipmentItems: [],
    laborItems: [],
    materialItems: [],
    discount: 0,
    addition: 0,
    totalAmount: 0,
    checklist: [],
    photos: [],
  },
  {
    id: 'os-31877-14',
    osNumber: '31877',
    clientId: 'cli-ita',
    clientName: 'ITA AIRWAYS',
    clientDocument: '',
    clientPhone: '(11) 98421-0099',
    clientEmail: 'groundops.gru@ita-airways.com',
    workLocation: 'Aeroporto / Pista',
    category: 'locacao',
    title: 'CANCELAMENTO DE VOO AZ675',
    description: 'Fechamento de voo e liberação da posição de pátio',
    status: 'aguardando_validacao',
    agentName: 'GABRIEL FERREIRA FONSECA 21032',
    agentBadge: '21032',
    startTime: '17:20',
    endTime: '19:54',
    durationMinutes: 154,
    durationFormatted: '2h 34m',
    quantity: '-',
    filledBy: 'Amanda Aparecida Vasco Cortez',
    createdBy: 'Amanda Aparecida Vasco Cortez',
    createdOrigin: 'campo_app',
    scheduledDate: '2026-08-11',
    createdAt: '2026-08-11T17:20:00.000Z',
    completedAt: '2026-08-11T19:54:00.000Z',
    technicianName: 'GABRIEL FERREIRA FONSECA 21032',
    canhotoUrl: 'https://drive.google.com/open?id=wfs-az675-14',
    equipmentItems: [],
    laborItems: [],
    materialItems: [],
    discount: 0,
    addition: 0,
    totalAmount: 0,
    checklist: [],
    photos: [],
  },
  // OS PMC 03656 - DELTA (Posição 101 - Proteção Cargas) - Registros reais da Planilha
  {
    id: 'os-pmc03656-1',
    osNumber: 'PMC 03656',
    clientId: 'cli-delta',
    clientName: 'DELTA',
    clientDocument: '',
    clientPhone: '',
    clientEmail: 'ops.gru@delta.com',
    workLocation: 'Posição 101',
    category: 'misto',
    title: 'Proteção cargas / Corte de carga',
    description: 'Proteção cargas e atendimento na posição 101',
    status: 'aguardando_validacao',
    agentName: 'Mario Santos',
    agentBadge: 'MS',
    startTime: '23:00',
    endTime: '00:00',
    durationMinutes: 60,
    durationFormatted: '1h 00m',
    quantity: '-',
    filledBy: 'Lilian Sampaio',
    createdBy: 'Lilian Sampaio',
    createdByRole: 'Encarregada de Rampa',
    createdOrigin: 'campo_app',
    scheduledDate: '2026-07-31',
    scheduledTime: '23:00',
    createdAt: '2026-07-31T23:00:00.000Z',
    completedAt: '2026-08-01T00:00:00.000Z',
    technicianName: 'Mario Santos',
    canhotoUrl: 'https://drive.google.com/open?id=wfs-pmc03656-01',
    equipmentItems: [],
    laborItems: [],
    materialItems: [],
    discount: 0,
    addition: 0,
    totalAmount: 0,
    checklist: [],
    photos: [],
  },
  {
    id: 'os-pmc03656-2',
    osNumber: 'PMC 03656',
    clientId: 'cli-delta',
    clientName: 'DELTA',
    clientDocument: '',
    clientPhone: '',
    clientEmail: 'ops.gru@delta.com',
    workLocation: 'Posição 101',
    category: 'misto',
    title: 'Proteção cargas / Corte de carga',
    description: 'Proteção cargas e apoio operacional',
    status: 'aguardando_validacao',
    agentName: 'Mario Santos',
    agentBadge: 'MS',
    startTime: '00:00',
    endTime: '05:00',
    durationMinutes: 300,
    durationFormatted: '5h 00m',
    quantity: '-',
    filledBy: 'Lilian Sampaio',
    createdBy: 'Lilian Sampaio',
    createdByRole: 'Encarregada de Rampa',
    createdOrigin: 'campo_app',
    scheduledDate: '2026-07-31',
    scheduledTime: '23:00',
    createdAt: '2026-08-01T00:00:00.000Z',
    completedAt: '2026-08-01T05:00:00.000Z',
    technicianName: 'Mario Santos',
    canhotoUrl: 'https://drive.google.com/open?id=wfs-pmc03656-02',
    equipmentItems: [],
    laborItems: [],
    materialItems: [],
    discount: 0,
    addition: 0,
    totalAmount: 0,
    checklist: [],
    photos: [],
  },
  {
    id: 'os-pmc03656-3',
    osNumber: 'PMC 03656',
    clientId: 'cli-delta',
    clientName: 'DELTA',
    clientDocument: '',
    clientPhone: '',
    clientEmail: 'ops.gru@delta.com',
    workLocation: 'Posição 101',
    category: 'misto',
    title: 'Proteção cargas / Corte de carga',
    description: 'Proteção cargas e movimentação de pátio',
    status: 'aguardando_validacao',
    agentName: 'Anderson Romano',
    agentBadge: 'AR',
    startTime: '05:00',
    endTime: '11:00',
    durationMinutes: 360,
    durationFormatted: '6h 00m',
    quantity: '-',
    filledBy: 'Lilian Sampaio',
    createdBy: 'Lilian Sampaio',
    createdByRole: 'Encarregada de Rampa',
    createdOrigin: 'campo_app',
    scheduledDate: '2026-07-31',
    scheduledTime: '23:00',
    createdAt: '2026-08-01T05:00:00.000Z',
    completedAt: '2026-08-01T11:00:00.000Z',
    technicianName: 'Anderson Romano',
    canhotoUrl: 'https://drive.google.com/open?id=wfs-pmc03656-03',
    equipmentItems: [],
    laborItems: [],
    materialItems: [],
    discount: 0,
    addition: 0,
    totalAmount: 0,
    checklist: [],
    photos: [],
  },
  {
    id: 'os-pmc03656-4',
    osNumber: 'PMC 03656',
    clientId: 'cli-delta',
    clientName: 'DELTA',
    clientDocument: '',
    clientPhone: '',
    clientEmail: 'ops.gru@delta.com',
    workLocation: 'Posição 101',
    category: 'misto',
    title: 'Proteção cargas / Corte de carga',
    description: 'Proteção cargas e fechamento de voo',
    status: 'aguardando_validacao',
    agentName: 'Antonio Almeida',
    agentBadge: 'AA',
    startTime: '11:00',
    endTime: '15:00',
    durationMinutes: 240,
    durationFormatted: '4h 00m',
    quantity: '-',
    filledBy: 'Lilian Sampaio',
    createdBy: 'Lilian Sampaio',
    createdByRole: 'Encarregada de Rampa',
    createdOrigin: 'campo_app',
    scheduledDate: '2026-07-31',
    scheduledTime: '23:00',
    createdAt: '2026-08-01T11:00:00.000Z',
    completedAt: '2026-08-01T15:00:00.000Z',
    technicianName: 'Antonio Almeida',
    canhotoUrl: 'https://drive.google.com/open?id=wfs-pmc03656-04',
    equipmentItems: [],
    laborItems: [],
    materialItems: [],
    discount: 0,
    addition: 0,
    totalAmount: 0,
    checklist: [],
    photos: [],
  },
  // OS 1 - Manutenção Corretiva (Atacado bom preço)
  {
    id: 'os-1',
    osNumber: '1',
    clientId: 'cli-atacado',
    clientName: 'Atacado bom preço',
    clientDocument: '15.238.396/0001-87',
    clientPhone: '11973129840',
    clientEmail: 'manutencao@atacadobompreco.com.br',
    workLocation: 'Av. Senador Salgado Filho, 1305, Centro - Guarulhos/SP',
    category: 'servico_tecnico',
    title: 'Limpeza de filtro realizada; Mold... Filtro, Suporte, Mangueira',
    description: 'Manutenção técnica preventiva/corretiva em sistema de filtragem e tubulação industrial.',
    status: 'em_andamento',
    technicianName: 'João C. Silva',
    agentName: 'João C. Silva',
    filledBy: 'João C. Silva',
    createdBy: 'João C. Silva',
    createdByRole: 'Técnico Especialista em Solo',
    createdOrigin: 'campo_app',
    scheduledDate: '2021-02-26',
    scheduledTime: '08:00',
    createdAt: '2021-02-26T08:00:00.000Z',
    canhotoUrl: 'https://drive.google.com/open?id=wfs-atacado-01',
    quantity: '-',
    equipmentItems: [],
    laborItems: [
      {
        id: 'lab-it-1',
        laborServiceId: 'lab-2',
        name: 'Técnico Eletromecânico: João C. Silva',
        unit: 'hora',
        quantity: 4,
        unitPrice: 0,
        technicianName: 'João C. Silva',
      }
    ],
    materialItems: [
      {
        id: 'mat-1',
        name: 'Filtro, Suporte, Mangueira',
        unit: 'cj',
        quantity: 1,
        unitPrice: 0,
      }
    ],
    discount: 0,
    addition: 0,
    totalAmount: 0,
    checklist: [
      { id: 'chk-1-1', task: 'Desmontagem e limpeza do conjunto filtrante', completed: true },
      { id: 'chk-1-2', task: 'Substituição do suporte e mangueira sob pressão', completed: false },
    ],
    photos: [],
    clientSignature: {
      signatureImage: sampleClientSignatureSVG,
      signerName: 'Fiscal Atacado Bom Preço',
      signerDocument: '15.238.396/0001-87',
      signerRole: 'Encarregado de Manutenção',
      signedAt: '2021-02-26T12:00:00.000Z',
    },
  },
  {
    id: 'os-100',
    osNumber: 'OS-2026-0045',
    clientId: 'cli-1',
    clientName: 'LATAM Airlines Brasil S.A.',
    clientDocument: '02.012.862/0001-60',
    clientPhone: '11984210099',
    clientEmail: 'ground.operations@latam.com',
    workLocation: 'Pátio 2 - Posição 12 (Hangar LATAM GRU)',
    category: 'misto',
    title: 'Locação GPU 90kVA + Operador GSE (Leitura OCR via Teams)',
    description: 'Alimentação elétrica 400Hz para acionamento de sistemas de cabine durante escala técnica.',
    status: 'aguardando_validacao',
    createdBy: 'Carlos Silva (Encarregado)',
    createdByRole: 'Encarregado de Campo & Pista',
    createdOrigin: 'teams_upload',
    teamsSenderName: 'Carlos Silva (via Microsoft Teams Grupo Rampa GRU)',
    teamsChannel: 'Canal Operações & Rampa WFS',
    createdAt: '2026-08-22T08:15:00.000Z',
    scheduledDate: '2026-08-22',
    technicianName: 'Rodrigo Vasconcelos',
    technicianPhone: '(11) 97722-1144',
    equipmentItems: [
      {
        id: 'item-eq-100',
        equipmentId: 'eq-1',
        name: 'Ground Power Unit (GPU) 90kVA 400Hz para Aeronaves',
        code: 'GPU-090',
        unit: 'diaria',
        quantity: 1,
        unitPrice: 1200.00,
        notes: 'Horímetro inicial 2.150h / Final 2.156h',
      }
    ],
    laborItems: [
      {
        id: 'item-lab-100',
        laborServiceId: 'lab-1',
        name: 'Operador de Equipamentos de Solo GSE Especializado',
        unit: 'hora',
        quantity: 6,
        unitPrice: 90.00,
        technicianName: 'Rodrigo Vasconcelos',
      }
    ],
    materialItems: [],
    discount: 0,
    addition: 0,
    totalAmount: 1740.00,
    checklist: [
      { id: 'chk-100-1', task: 'Inspeção de segurança FOD', completed: true, completedAt: '2026-08-22T08:30:00.000Z' },
      { id: 'chk-100-2', task: 'Acoplamento com teste de 400Hz', completed: true, completedAt: '2026-08-22T08:45:00.000Z' },
    ],
    photos: [
      {
        id: 'p-100',
        url: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=600&q=80',
        title: 'Foto do Canhoto de Campo enviada no Teams',
        category: 'canhoto',
        timestamp: '2026-08-22T08:15:00.000Z',
      }
    ],
    auditLogs: [
      {
        id: 'log-100-1',
        action: 'teams_upload',
        userName: 'Carlos Silva (via Teams)',
        userRole: 'Encarregado de Pista',
        timestamp: '2026-08-22T08:15:00.000Z',
        details: 'Foto da OS enviada no grupo do Microsoft Teams. IA realizou OCR dos dados automaticamente.',
        origin: 'teams_upload',
      }
    ],
  },
  {
    id: 'os-101',
    osNumber: 'OS-2026-0042',
    clientId: 'cli-1',
    clientName: 'LATAM Airlines Brasil S.A.',
    clientDocument: '02.012.862/0001-60',
    clientPhone: '11984210099',
    clientEmail: 'ground.operations@latam.com',
    workLocation: 'Pátio 2 - Posição 24 (Hangar LATAM GRU)',
    category: 'misto',
    title: 'Locação GPU 90kVA + Operador GSE para Atendimento Aeronave B777',
    description: 'Fornecimento de energia 400Hz para manutenção de cabine e testes elétricos no Boeing 777.',
    status: 'concluida',
    createdBy: 'Carlos Silva (Encarregado)',
    createdByRole: 'Encarregado de Campo & Pista',
    createdOrigin: 'campo_app',
    validatedBy: 'Mariana Costa (Analista Faturamento)',
    validatedAt: '2026-08-20T09:00:00.000Z',
    createdAt: '2026-08-19T08:00:00.000Z',
    scheduledDate: '2026-08-19',
    completedAt: '2026-08-19T18:45:00.000Z',
    technicianName: 'Rodrigo Vasconcelos',
    technicianPhone: '(11) 97722-1144',
    equipmentItems: [
      {
        id: 'item-eq-1',
        equipmentId: 'eq-1',
        name: 'Ground Power Unit (GPU) 90kVA 400Hz para Aeronaves',
        code: 'GPU-090',
        unit: 'diaria',
        quantity: 1,
        unitPrice: 1200.00,
        notes: 'Horímetro inicial 2.140h / Final 2.148h',
      }
    ],
    laborItems: [
      {
        id: 'item-lab-1',
        laborServiceId: 'lab-1',
        name: 'Operador de Equipamentos de Solo GSE Especializado',
        unit: 'hora',
        quantity: 8,
        unitPrice: 90.00,
        technicianName: 'Rodrigo Vasconcelos',
        notes: 'Turno integral de acompanhamento técnico',
      }
    ],
    materialItems: [
      {
        id: 'item-mat-1',
        name: 'Cabo de conexão aeronáutica 400Hz e calços de segurança',
        unit: 'cj',
        quantity: 1,
        unitPrice: 120.00,
      }
    ],
    discount: 0,
    addition: 0,
    totalAmount: 2040.00,
    checklist: [
      { id: 'chk-1', task: 'Inspeção de segurança FOD na posição da aeronave', completed: true, completedAt: '2026-08-19T08:30:00.000Z' },
      { id: 'chk-2', task: 'Acoplamento da GPU e teste de frequência 400Hz / 115V', completed: true, completedAt: '2026-08-19T09:00:00.000Z' },
      { id: 'chk-3', task: 'Acompanhamento do consumo de energia durante testes de aviônicos', completed: true, completedAt: '2026-08-19T14:15:00.000Z' },
      { id: 'chk-4', task: 'Desconexão segura com calços de proteção na rampa', completed: true, completedAt: '2026-08-19T18:30:00.000Z' },
      { id: 'chk-5', task: 'Coleta de assinatura digital do coordenador de pista LATAM', completed: true, completedAt: '2026-08-19T18:45:00.000Z' },
    ],
    photos: [
      {
        id: 'p-1',
        url: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=600&q=80',
        title: 'GPU 90kVA conectada no conector de força da aeronave',
        category: 'equipamento',
        timestamp: '2026-08-19T09:10:00.000Z',
        notes: 'Tensão estabilizada em 115V 400Hz',
      }
    ],
    clientSignature: {
      signatureImage: sampleClientSignatureSVG,
      signerName: 'Marcelo Ribeiro',
      signerDocument: '298.412.890-33',
      signerRole: 'Coordenador de Manutenção LATAM',
      signedAt: '2026-08-19T18:45:12.000Z',
      locationGeo: {
        latitude: -23.4356,
        longitude: -46.4731,
        addressDescription: 'Aeroporto de Guarulhos - Pátio Hangar LATAM (GPS Verificado)',
      },
    },
    technicianSignature: {
      signatureImage: sampleTechSignatureSVG,
      signerName: 'Rodrigo Vasconcelos',
      signerDocument: '412.580.119-02',
      signerRole: 'Técnico de GSE - WFS',
      signedAt: '2026-08-19T18:46:00.000Z',
    },
    termsAcceptedText: 'Serviço prestado conforme padrões IATA/WFS e GPU entregue sem avarias.',
    billingNotes: 'Aguardando emissão da fatura para faturar no vencimento de 15 dias.',
    auditLogs: [
      {
        id: 'log-101-1',
        action: 'criacao_campo',
        userName: 'Carlos Silva',
        userRole: 'Encarregado de Campo',
        timestamp: '2026-08-19T08:00:00.000Z',
        details: 'Ordem de serviço aberta no app de campo.',
        origin: 'campo_app',
      },
      {
        id: 'log-101-2',
        action: 'assinatura_cliente',
        userName: 'Marcelo Ribeiro (LATAM)',
        userRole: 'Cliente / Fiscal de Obra',
        timestamp: '2026-08-19T18:45:12.000Z',
        details: 'Assinatura digital coletada no tablet/celular com geolocalização.',
        origin: 'campo_app',
      },
      {
        id: 'log-101-3',
        action: 'validacao_faturamento',
        userName: 'Mariana Costa',
        userRole: 'Analista de Faturamento',
        timestamp: '2026-08-20T09:00:00.000Z',
        details: 'Medição e valores conferidos e aprovados para cobrança.',
        origin: 'painel_web',
      },
    ],
  },
  {
    id: 'os-102',
    osNumber: 'OS-2026-0043',
    clientId: 'cli-2',
    clientName: 'Azul Linhas Aéreas Brasileiras S.A.',
    clientDocument: '09.296.295/0001-60',
    clientPhone: '11973129840',
    clientEmail: 'operacoes.cargo@voeazul.com.br',
    workLocation: 'Terminal TECA Viracopos VCP',
    category: 'mao_de_obra',
    title: 'Operação Especial de Paletização e Carregamento de Cargas Frágeis',
    description: 'Equipe de apoio para triagem e montagem de 6 pallets ULD para voo cargueiro.',
    status: 'concluida',
    createdBy: 'Lucas Mendes',
    createdByRole: 'Técnico Especialista em Solo',
    createdOrigin: 'campo_app',
    createdAt: '2026-08-20T07:30:00.000Z',
    scheduledDate: '2026-08-20',
    completedAt: '2026-08-20T19:30:00.000Z',
    technicianName: 'Márcio Souza & Equipe WFS',
    technicianPhone: '(11) 98112-9900',
    equipmentItems: [
      {
        id: 'item-eq-2',
        equipmentId: 'eq-3',
        name: 'Esteira Carregadora de Bagagens Autopropelida (Belt Loader)',
        code: 'EST-020',
        unit: 'diaria',
        quantity: 1,
        unitPrice: 850.00,
      }
    ],
    laborItems: [
      {
        id: 'item-lab-2',
        laborServiceId: 'lab-5',
        name: 'Equipe Especializada de Carga Aérea (1 Líder + 3 Auxiliares)',
        unit: 'diaria',
        quantity: 1,
        unitPrice: 1600.00,
        technicianName: 'Márcio Souza e Equipe WFS',
      }
    ],
    materialItems: [
      {
        id: 'item-mat-2',
        name: 'Redes de retenção de carga e fitas aeronáuticas certificadas',
        unit: 'cj',
        quantity: 1,
        unitPrice: 250.00,
      }
    ],
    discount: 0,
    addition: 0,
    totalAmount: 2700.00,
    checklist: [
      { id: 'chk-201', task: 'Conferência de documentação de carga perigosa (DGR)', completed: true, completedAt: '2026-08-20T08:00:00.000Z' },
      { id: 'chk-202', task: 'Montagem e amarração dos pallets conforme padrão WFS', completed: true, completedAt: '2026-08-20T15:30:00.000Z' },
      { id: 'chk-203', task: 'Pesagem e etiquetagem dos ULDs', completed: true, completedAt: '2026-08-20T18:00:00.000Z' },
      { id: 'chk-204', task: 'Assinatura digital do encarregado de rampa Azul', completed: true, completedAt: '2026-08-20T19:30:00.000Z' },
    ],
    photos: [
      {
        id: 'p-201',
        url: 'https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?auto=format&fit=crop&w=600&q=80',
        title: 'Pallet ULD montado e travado',
        category: 'durante',
        timestamp: '2026-08-20T16:00:00.000Z',
      }
    ],
    clientSignature: {
      signatureImage: sampleClientSignatureSVG,
      signerName: 'Carlos Alberto Mendes',
      signerDocument: '183.921.440-19',
      signerRole: 'Supervisor de Turno Azul Cargo',
      signedAt: '2026-08-20T19:30:45.000Z',
      locationGeo: {
        latitude: -23.0074,
        longitude: -47.1345,
        addressDescription: 'Viracopos - Campinas / TECA Azul',
      },
    },
    technicianSignature: {
      signatureImage: sampleTechSignatureSVG,
      signerName: 'Márcio Souza',
      signerDocument: '319.450.881-00',
      signerRole: 'Líder Operacional WFS',
      signedAt: '2026-08-20T19:32:00.000Z',
    },
  },
  {
    id: 'os-103',
    osNumber: 'OS-2026-0044',
    clientId: 'cli-3',
    clientName: 'Lufthansa Cargo AG - Filial Brasil',
    clientDocument: '33.123.456/0001-77',
    clientPhone: '11999887766',
    clientEmail: 'handling.gru@dlh.de',
    workLocation: 'TECA GRU - Doca 08',
    category: 'locacao',
    title: 'Locação Trator de Reboque GSE + 2 Carretas para Pátio',
    description: 'Movimentação contínua de cargas farmacêuticas termo-controladas entre o TECA e o pátio.',
    status: 'em_andamento',
    createdBy: 'Carlos Silva',
    createdByRole: 'Encarregado de Campo',
    createdOrigin: 'campo_app',
    createdAt: '2026-08-21T07:00:00.000Z',
    scheduledDate: '2026-08-21',
    technicianName: 'Valdir Sanches (Operador WFS)',
    technicianPhone: '(11) 99123-8877',
    equipmentItems: [
      {
        id: 'item-eq-3',
        equipmentId: 'eq-2',
        name: 'Trator de Reboque de Pista (Baggage Tow Tractor)',
        code: 'TRB-015',
        unit: 'diaria',
        quantity: 1,
        unitPrice: 950.00,
      }
    ],
    laborItems: [
      {
        id: 'item-lab-3',
        laborServiceId: 'lab-1',
        name: 'Operador de Equipamentos de Solo GSE Especializado',
        unit: 'hora',
        quantity: 8,
        unitPrice: 90.00,
        technicianName: 'Valdir Sanches',
      }
    ],
    materialItems: [],
    discount: 50.00,
    addition: 0,
    totalAmount: 1620.00,
    checklist: [
      { id: 'chk-301', task: 'Inspeção pré-operacional do trator e freios', completed: true, completedAt: '2026-08-21T07:30:00.000Z' },
      { id: 'chk-302', task: 'Início do translado com carretas refrigeradas', completed: true, completedAt: '2026-08-21T08:15:00.000Z' },
      { id: 'chk-303', task: 'Finalização do voo e coleta de assinatura', completed: false },
    ],
    photos: [],
  },
  {
    id: 'os-104',
    osNumber: 'OS-2026-0040',
    clientId: 'cli-4',
    clientName: 'CCR Aeroportos S.A.',
    clientDocument: '14.765.432/0001-55',
    clientPhone: '19981234567',
    clientEmail: 'manutencao.pista@grupoccr.com.br',
    workLocation: 'Pista de Taxiway - Aeroporto de Campinas',
    category: 'misto',
    title: 'Manutenção Preventiva de Balizamento Noturno & Gerador de Emergência',
    description: 'Revisão técnica de circuitos de cabeceira de pista e teste sob carga com gerador silenciado.',
    status: 'faturada',
    createdBy: 'Lucas Mendes',
    createdByRole: 'Técnico Especialista',
    createdOrigin: 'campo_app',
    createdAt: '2026-08-10T09:00:00.000Z',
    scheduledDate: '2026-08-10',
    completedAt: '2026-08-11T16:00:00.000Z',
    invoicedAt: '2026-08-12T10:00:00.000Z',
    technicianName: 'Fernando Alencar',
    technicianPhone: '(19) 99881-2233',
    equipmentItems: [
      {
        id: 'item-eq-4',
        equipmentId: 'eq-4',
        name: 'Grupo Gerador Silenciado 50 kVA Diesel',
        code: 'GER-050',
        unit: 'diaria',
        quantity: 2,
        unitPrice: 480.00,
      }
    ],
    laborItems: [
      {
        id: 'item-lab-4',
        laborServiceId: 'lab-2',
        name: 'Técnico de Manutenção Eletromecânica / GSE',
        unit: 'hora',
        quantity: 16,
        unitPrice: 110.00,
      }
    ],
    materialItems: [],
    discount: 0,
    addition: 0,
    totalAmount: 2720.00,
    invoiceId: 'inv-201',
    invoiceNumber: 'FAT-2026-0038',
    paymentDueDate: '2026-09-01',
    paymentMethod: 'boleto',
    checklist: [
      { id: 'chk-401', task: 'Inspeção de 42 luminárias LED de taxiway', completed: true, completedAt: '2026-08-10T14:00:00.000Z' },
      { id: 'chk-402', task: 'Teste de comutação automática com gerador', completed: true, completedAt: '2026-08-11T15:30:00.000Z' },
    ],
    photos: [],
    clientSignature: {
      signatureImage: sampleClientSignatureSVG,
      signerName: 'Fernando Souza',
      signerDocument: '304.591.229-84',
      signerRole: 'Engenheiro de Infraestrutura CCR',
      signedAt: '2026-08-11T16:00:00.000Z',
    },
  },
  {
    id: 'os-105',
    osNumber: 'OS-2026-0038',
    clientId: 'cli-1',
    clientName: 'LATAM Airlines Brasil S.A.',
    clientDocument: '02.012.862/0001-60',
    clientPhone: '11984210099',
    clientEmail: 'ground.operations@latam.com',
    workLocation: 'Hangar de Manutenção LATAM GRU',
    category: 'locacao',
    title: 'Locação Plataforma Tesoura Elétrica 10m (5 Diárias)',
    description: 'Trabalho em altura para inspeção de flaps e leme de cauda de aeronave A321.',
    status: 'paga',
    createdBy: 'Carlos Silva',
    createdByRole: 'Encarregado de Campo',
    createdOrigin: 'campo_app',
    createdAt: '2026-08-01T08:00:00.000Z',
    scheduledDate: '2026-08-01',
    completedAt: '2026-08-06T17:00:00.000Z',
    invoicedAt: '2026-08-06T18:00:00.000Z',
    paidAt: '2026-08-10T11:20:00.000Z',
    technicianName: 'Rodrigo Vasconcelos',
    equipmentItems: [
      {
        id: 'item-eq-5',
        equipmentId: 'eq-6',
        name: 'Plataforma Tesoura Elétrica 10m (Manlift)',
        code: 'PLT-010',
        unit: 'diaria',
        quantity: 5,
        unitPrice: 450.00,
      }
    ],
    laborItems: [],
    materialItems: [],
    discount: 0,
    addition: 0,
    totalAmount: 2250.00,
    invoiceId: 'inv-200',
    invoiceNumber: 'FAT-2026-0035',
    paymentDueDate: '2026-08-10',
    paymentMethod: 'pix',
    checklist: [
      { id: 'chk-501', task: 'Entrega técnica e vistoria de baterias', completed: true, completedAt: '2026-08-01T09:00:00.000Z' },
      { id: 'chk-502', task: 'Devolução com checklist de integridade aprovado', completed: true, completedAt: '2026-08-06T16:45:00.000Z' },
    ],
    photos: [],
    clientSignature: {
      signatureImage: sampleClientSignatureSVG,
      signerName: 'Marcelo Ribeiro',
      signerDocument: '298.412.890-33',
      signerRole: 'Coordenador LATAM',
      signedAt: '2026-08-06T17:00:00.000Z',
    },
  }
];

export const initialInvoices: Invoice[] = [
  {
    id: 'inv-200',
    invoiceNumber: 'FAT-2026-0035',
    clientId: 'cli-1',
    clientName: 'LATAM Airlines Brasil S.A.',
    clientDocument: '02.012.862/0001-60',
    osIds: ['os-105'],
    osNumbers: ['OS-2026-0038'],
    issueDate: '2026-08-06T18:00:00.000Z',
    dueDate: '2026-08-10',
    totalAmount: 2250.00,
    status: 'paga',
    paymentMethod: 'pix',
    pixKey: '02481932000150',
    sentAt: '2026-08-06T18:10:00.000Z',
    paidAt: '2026-08-10T11:20:00.000Z',
    notes: 'Liquidado via PIX WFS Brasil com comprovante bancário emitido.',
  },
  {
    id: 'inv-201',
    invoiceNumber: 'FAT-2026-0038',
    clientId: 'cli-4',
    clientName: 'CCR Aeroportos S.A.',
    clientDocument: '14.765.432/0001-55',
    osIds: ['os-104'],
    osNumbers: ['OS-2026-0040'],
    issueDate: '2026-08-12T10:00:00.000Z',
    dueDate: '2026-09-01',
    totalAmount: 2720.00,
    status: 'enviada',
    paymentMethod: 'boleto',
    bankDetails: 'Banco Santander (033) - Linha digitável registrada',
    sentAt: '2026-08-12T10:15:00.000Z',
    notes: 'Enviado por e-mail para controladoria CCR.',
  }
];
