import { AppUser, Client, CompanyProfile, Equipment, Invoice, LaborService, ServiceOrder } from './types';

export const initialUsers: AppUser[] = [
  {
    id: 'usr-master-ivo',
    name: 'Ivo (Master Administrador)',
    email: 'ivoaltctrl@gmail.com',
    section: 'Diretoria & Governança',
    roleTitle: 'Administrador Geral & Mestre',
    department: 'Governança & TI',
    password: 'admin',
    privilege: 'administrador',
    privilegeLabel: 'Administrador Master Geral',
    canValidateBilling: true,
    canDeleteOS: true,
    canAccessExecutive: true,
    canAccessSettings: true,
    mustChangePassword: false,
    firstAccess: false,
    active: true,
    createdAt: '2026-01-01T00:00:00.000Z',
    role: 'master_ti',
    roleLabel: 'Administrador de TI & Governança',
    phone: '(11) 99999-0000',
    avatarColor: 'bg-slate-900',
  },
];

export const initialCompany: CompanyProfile = {
  name: 'WFS Brasil Serviços Aeroportuários e Operações Industriais Ltda',
  tradeName: 'WFS - A SATS COMPANY',
  cnpj: '02.481.932/0001-50',
  stateRegistration: '114.920.301.119',
  phone: '(11) 4002-8922',
  email: 'faturamento.brasil@wfs.aero',
  address: 'Aeroporto Internacional de Guarulhos - Terminal de Cargas / Hangar WFS',
  cityState: 'Guarulhos - SP',
  pixKey: '02481932000150',
  bankInfo: 'Banco Santander (033) - Ag: 2240 / CC: 93810-4',
  defaultTerms: 'O cliente declara estar ciente do recebimento dos equipamentos em perfeito estado de funcionamento e/ou da prestação dos serviços especializados discriminados nesta Ordem de Serviço conforme os padrões operacionais WFS. A recusa injustificada de aceite não desobriga o pagamento das diárias e horas apontadas.',
  billingAlertHours: 24,
};

export const initialClients: Client[] = [
  {
    id: 'cli-ita',
    name: 'ITA AIRWAYS',
    tradeName: 'ITA Airways Brasil / Operações GRU',
    document: '33.912.876/0001-90',
    email: 'groundops.gru@ita-airways.com',
    phone: '11984210099',
    contactPerson: 'Amanda Aparecida Vasco Cortez',
    address: {
      street: 'Aeroporto Internacional de Guarulhos',
      number: 'TPS3',
      neighborhood: 'Cumbica',
      city: 'Guarulhos',
      state: 'SP',
      zipCode: '07190-100',
      workSiteName: 'GRU - Terminal de Passageiros & Pátio',
    },
    paymentTermsDays: 15,
    notes: 'Serviços auxiliares de transporte aéreo e atendimento de rampa em voos e cancelamentos.',
    createdAt: '2026-08-11T14:34:00.000Z',
  },
  {
    id: 'cli-atacado',
    name: 'Atacado bom preço',
    tradeName: 'Atacado Bom Preço Distribuição Ltda',
    document: '15.238.396/0001-87',
    email: 'manutencao@atacadobompreco.com.br',
    phone: '11973129840',
    contactPerson: 'João C. Silva',
    address: {
      street: 'Av. Senador Salgado Filho',
      number: '1305',
      neighborhood: 'Centro',
      city: 'Guarulhos',
      state: 'SP',
      zipCode: '07115-000',
      workSiteName: 'Centro de Distribuição Guarulhos',
    },
    paymentTermsDays: 30,
    notes: 'Manutenção corretiva com troca de filtros, suporte e mangueiras.',
    createdAt: '2021-02-26T08:00:00.000Z',
  },
  {
    id: 'cli-1',
    name: 'LATAM Airlines Brasil S.A.',
    tradeName: 'LATAM Cargo & Ground Operations',
    document: '02.012.862/0001-60',
    email: 'ground.operations@latam.com',
    phone: '11984210099',
    contactPerson: 'Coord. Marcelo Ribeiro',
    address: {
      street: 'Rod. Hélio Smidt, s/n',
      number: 'Hangar 04',
      neighborhood: 'Cumbica',
      city: 'Guarulhos',
      state: 'SP',
      zipCode: '07190-100',
      workSiteName: 'Pátio 2 - Pista & Hangar LATAM',
    },
    paymentTermsDays: 15,
    notes: 'Exige canhoto de OS assinado pelo supervisor de pátio na hora para autorizar a medição.',
    createdAt: '2026-01-10T10:00:00.000Z',
  },
  {
    id: 'cli-2',
    name: 'Azul Linhas Aéreas Brasileiras S.A.',
    tradeName: 'Azul Cargo Express',
    document: '09.296.295/0001-60',
    email: 'operacoes.cargo@voeazul.com.br',
    phone: '11973129840',
    contactPerson: 'Carlos Alberto (Supervisor de Turno)',
    address: {
      street: 'Av. Marcos Penteado de Ulhôa Rodrigues, 939',
      number: 'Ed. Castelo',
      neighborhood: 'Tamboré',
      city: 'Barueri',
      state: 'SP',
      zipCode: '06460-040',
      workSiteName: 'TECA Viracopos (VCP) - Campinas',
    },
    paymentTermsDays: 30,
    notes: 'Faturamento quinzenal agrupado por centro de custo de pista.',
    createdAt: '2026-01-15T14:30:00.000Z',
  },
  {
    id: 'cli-3',
    name: 'Lufthansa Cargo AG - Filial Brasil',
    tradeName: 'Lufthansa Cargo Handling',
    document: '33.123.456/0001-77',
    email: 'handling.gru@dlh.de',
    phone: '11999887766',
    contactPerson: 'Klaus Mueller',
    address: {
      street: 'Rod. Pres. Dutra, km 215',
      number: 'Terminal TECA',
      neighborhood: 'Cumbica',
      city: 'Guarulhos',
      state: 'SP',
      zipCode: '07180-000',
      workSiteName: 'TECA GRU - Doca 08',
    },
    paymentTermsDays: 7,
    notes: 'Prioridade máxima em pontualidade de entrega dos tratores de pátio.',
    createdAt: '2026-01-20T08:00:00.000Z',
  },
  {
    id: 'cli-4',
    name: 'CCR Aeroportos S.A.',
    tradeName: 'Concessionária do Aeroporto de Curitiba & BH',
    document: '14.765.432/0001-55',
    email: 'manutencao.pista@grupoccr.com.br',
    phone: '19981234567',
    contactPerson: 'Eng. Fernando Souza',
    address: {
      street: 'Av. Rocha Pombo, s/n',
      number: 'Administração',
      neighborhood: 'Águas Belas',
      city: 'São José dos Pinhais',
      state: 'PR',
      zipCode: '83010-900',
      workSiteName: 'Pista de Pouso e Pátio Central',
    },
    paymentTermsDays: 30,
    notes: 'Exige laudo técnico assinado e fotos de antes/depois da manutenção eletromecânica.',
    createdAt: '2026-02-01T11:20:00.000Z',
  }
];

export const initialEquipments: Equipment[] = [
  {
    id: 'eq-1',
    code: 'GPU-090',
    name: 'Ground Power Unit (GPU) 90kVA 400Hz para Aeronaves',
    category: 'Energia GSE Aeroportuária',
    dailyRate: 1200.00,
    hourlyRate: 180.00,
    status: 'disponivel',
    serialNumber: 'GPU-2024-9981',
    specifications: 'Saída 115/200V 400Hz Trifásico, motor Cummins Diesel silenciado, cabo padrão aeronáutico.',
  },
  {
    id: 'eq-2',
    code: 'TRB-015',
    name: 'Trator de Reboque de Pista (Baggage Tow Tractor)',
    category: 'Movimentação GSE',
    dailyRate: 950.00,
    hourlyRate: 140.00,
    status: 'em_uso',
    serialNumber: 'TR-EL-401',
    specifications: 'Capacidade de tração de até 25 toneladas de carga/carretas de bagagem, motor elétrico com bateria íon-lítio.',
  },
  {
    id: 'eq-3',
    code: 'EST-020',
    name: 'Esteira Carregadora de Bagagens Autopropelida (Belt Loader)',
    category: 'Carga & Descarga',
    dailyRate: 850.00,
    hourlyRate: 130.00,
    status: 'disponivel',
    serialNumber: 'BL-884-2023',
    specifications: 'Elevação hidráulica ajustável até 4.3m, compatível com narrow-body e wide-body.',
  },
  {
    id: 'eq-4',
    code: 'GER-050',
    name: 'Grupo Gerador Silenciado 50 kVA Diesel',
    category: 'Geradores Industriais',
    dailyRate: 480.00,
    monthlyRate: 7200.00,
    status: 'disponivel',
    serialNumber: 'GG-50-2022',
    specifications: 'Cabine silenciada 68dB, tanque de 150L, painel digital de comando.',
  },
  {
    id: 'eq-5',
    code: 'MNC-012',
    name: 'Caminhão Munck 12 Toneladas com Operador',
    category: 'Içamento Pesado',
    dailyRate: 1800.00,
    hourlyRate: 220.00,
    status: 'disponivel',
    serialNumber: 'MNC-VOLVO-77',
    specifications: 'Alcance vertical de 18 metros, capacidade máxima 12t no pé e 1.8t na ponta.',
  },
  {
    id: 'eq-6',
    code: 'PLT-010',
    name: 'Plataforma Tesoura Elétrica 10m (Manlift)',
    category: 'Trabalho em Altura',
    dailyRate: 450.00,
    monthlyRate: 5800.00,
    status: 'disponivel',
    serialNumber: 'PLT-JLG-102',
    specifications: 'Altura de trabalho 10m, capacidade 230kg, pneus não marcantes para hangares.',
  }
];

export const initialLaborServices: LaborService[] = [
  {
    id: 'lab-1',
    code: 'MO-GSE-01',
    name: 'Operador de Equipamentos de Solo GSE Especializado',
    category: 'Operação Aeroportuária',
    unit: 'hora',
    unitPrice: 90.00,
    description: 'Profissional credenciado pela ANAC e INFRAERO com credencial de pista válida.',
  },
  {
    id: 'lab-2',
    code: 'MO-GSE-02',
    name: 'Técnico de Manutenção Eletromecânica / GSE',
    category: 'Manutenção Técnica',
    unit: 'hora',
    unitPrice: 110.00,
    description: 'Diagnóstico e reparo preventivo/corretivo em esteiras, tratores, geradores e GPUs.',
  },
  {
    id: 'lab-3',
    code: 'MO-IND-03',
    name: 'Soldador TIG / MIG Industrial com Certificação',
    category: 'Serralheria & Estrutura',
    unit: 'diaria',
    unitPrice: 550.00,
    description: 'Soldagem de alta precisão em tubulações e estruturas metálicas de hangares.',
  },
  {
    id: 'lab-4',
    code: 'MO-ENG-04',
    name: 'Engenheiro de Operações & Emissão de ART Técnica',
    category: 'Engenharia',
    unit: 'servico_fechado',
    unitPrice: 1200.00,
    description: 'Vistoria técnica presencial com laudo de conformidade e responsabilidade técnica.',
  },
  {
    id: 'lab-5',
    code: 'MO-CARGO-05',
    name: 'Equipe Especializada de Carga Aérea (1 Líder + 3 Auxiliares)',
    category: 'Carga & Descarga TECA',
    unit: 'diaria',
    unitPrice: 1600.00,
    description: 'Montagem de pallets aeronáuticos ULD e amarração com redes certificadas IATA.',
  }
];

const sampleClientSignatureSVG = `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="300" height="100" viewBox="0 0 300 100"><path d="M 20 60 Q 60 10, 100 40 T 180 30 T 260 70 M 70 80 L 220 75" stroke="%23E5232A" stroke-width="3" fill="none" stroke-linecap="round"/></svg>`;
const sampleTechSignatureSVG = `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="300" height="100" viewBox="0 0 300 100"><path d="M 30 70 Q 70 20, 120 50 Q 180 80, 240 30 M 100 30 L 150 90" stroke="%230F172A" stroke-width="3" fill="none" stroke-linecap="round"/></svg>`;

export const initialOrders: ServiceOrder[] = [];

export const initialInvoices: Invoice[] = [
  {
    id: 'inv-200',
    invoiceNumber: 'FAT-2026-0035',
    clientId: 'cli-1',
    clientName: 'LATAM Airlines Brasil S.A.',
    clientDocument: '02.012.862/0001-60',
    osIds: ['os-105'],
    osNumbers: ['OS-2026-0038'],
    issueDate: '2026-08-06T18:00:00.000Z',
    dueDate: '2026-08-10',
    totalAmount: 2250.00,
    status: 'paga',
    paymentMethod: 'pix',
    pixKey: '02481932000150',
    sentAt: '2026-08-06T18:10:00.000Z',
    paidAt: '2026-08-10T11:20:00.000Z',
    notes: 'Liquidado via PIX WFS Brasil com comprovante bancário emitido.',
  },
  {
    id: 'inv-201',
    invoiceNumber: 'FAT-2026-0038',
    clientId: 'cli-4',
    clientName: 'CCR Aeroportos S.A.',
    clientDocument: '14.765.432/0001-55',
    osIds: ['os-104'],
    osNumbers: ['OS-2026-0040'],
    issueDate: '2026-08-12T10:00:00.000Z',
    dueDate: '2026-09-01',
    totalAmount: 2720.00,
    status: 'enviada',
    paymentMethod: 'boleto',
    bankDetails: 'Banco Santander (033) - Linha digitável registrada',
    sentAt: '2026-08-12T10:15:00.000Z',
    notes: 'Enviado por e-mail para controladoria CCR.',
  }
];
